server:
  port: 8097

spring:
  datasource:
    url: jdbc:postgresql://90.156.208.88:5432/bruansk_final
    username: bruansk
    password: bruansk
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database: postgresql

  mail:
    host: smtp.gmail.com
    mail: port=587
    username: polenok@bgitu.ru
    password: d&4bXBWAmamot
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true




